import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '@styles/Home.module.css';
import React, { useState } from 'react';
import {
  useGetUsersQuery,
  useAddUserMutation,
  useUpdateUserMutation,
  useDeleteUserMutation,
} from '@src/store/services/userApi';
import BirthdayCard from '@src/components/BirthdayCard';
import { Button, Modal, Group } from '@mantine/core';

const Home: NextPage = () => {
  const [user, setUser] = useState('');
  const [birthday, setBirthday] = useState('');
  const [id, setId] = useState(0);
  const [openedNew, setOpenedNew] = useState(false);
  const [openedUpdate, setOpenedUpdate] = useState(false);
  const { data: users, isLoading, isSuccess, isError, error } = useGetUsersQuery(1);
  const [addUser] = useAddUserMutation();
  const [updateUser] = useUpdateUserMutation();
  const [deleteUser] = useDeleteUserMutation();

  const handleSubmit = (e: React.SyntheticEvent<HTMLFormElement>) => {
    e.preventDefault();
    addUser({ name: user, birthday: birthday });
    setUser('');
    setBirthday('');
  };

  const handleUpdate = (e: React.SyntheticEvent<HTMLFormElement>) => {
    e.preventDefault();
    updateUser({ id: id, name: user, birthday: birthday });
    setId(0);
    setUser('');
    setBirthday('');
    setOpenedUpdate(false);
  };

  let content;

  if (isLoading) {
    content = <p>Loading....</p>;
  } else if (isSuccess) {
    content = users.data.map((user: any) => {
      return (
        <div
          onClick={() => {
            setId(user.id);
            setOpenedUpdate(true);
            console.log('ID!!!: ', id);
          }}
          key={user.id}
        >
          <BirthdayCard name={user.name} birthday={user.birthday} />
        </div>
      );
    });
  } else if (isError) {
    content = <p>{error.toString()}</p>;
  }

  return (
    <div className={styles.container}>
      <Modal opened={openedNew} onClose={() => setOpenedNew(false)} title="New Birthday">
        <form onSubmit={handleSubmit}>
          <label htmlFor="new-user">Enter a new birthday</label>
          <div className="new-user">
            <input
              type="text"
              id="new-user"
              value={user}
              onChange={e => setUser(e.target.value)}
              placeholder="Enter birthday name"
            />
            <input
              type="text"
              id="new-bithday"
              value={birthday}
              onChange={e => setBirthday(e.target.value)}
              placeholder="Enter birthday date"
            />
          </div>
          <button onClick={() => setOpenedNew(false)}>Submit</button>
        </form>
      </Modal>

      <Modal opened={openedUpdate} onClose={() => setOpenedUpdate(false)} title="New Birthday">
        <form onSubmit={handleUpdate}>
          <label htmlFor="new-user">Enter a new birthday</label>
          <div className="new-user">
            <input
              type="text"
              id="new-user"
              value={user}
              onChange={e => setUser(e.target.value)}
              placeholder="Enter birthday name"
            />
            <input
              type="text"
              id="new-user"
              value={birthday}
              onChange={e => setBirthday(e.target.value)}
              placeholder="Enter birthday date"
            />
          </div>
          <button>Submit</button>
          <Button
            color={'red'}
            style={{ margin: 5 }}
            onClick={() => {
              deleteUser(id);
              setOpenedUpdate(false);
            }}
          >
            Delete
          </Button>
        </form>
      </Modal>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Birthdays!</a>
        </h1>
      </main>
      <Group position="center">
        <Button onClick={() => setOpenedNew(true)}>New BirthDay!</Button>
      </Group>
      <div className={styles.grid}>{content}</div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Manuel Bojacà FullStack JavaScript developer
        </a>
      </footer>
    </div>
  );
};

export default Home;
